# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

In [2]:
randomArr= np.random.randint(1,999,size=(3,3,3))

randomArr

array([[[979, 720, 785],
        [224, 964, 296],
        [689, 633, 429]],

       [[376, 674, 734],
        [ 21, 368, 496],
        [156, 141, 620]],

       [[  5, 698, 995],
        [878, 190, 717],
        [ 86, 111, 791]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
arr=np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [20]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [16]:
arr1=np.random.random((5,5))
print("Original array is \n",arr1)
from sklearn.preprocessing import normalize
arr2=normalize(arr1)
print("Normalised array is \n",arr2)

Original array is 
 [[0.0673155  0.08132167 0.38122786 0.92981903 0.92782866]
 [0.17561317 0.46964439 0.4426341  0.78183939 0.49191063]
 [0.46062067 0.10246624 0.96744715 0.20614924 0.96765453]
 [0.30251878 0.82904122 0.89911386 0.33710911 0.31672341]
 [0.00710128 0.53821252 0.4373564  0.77268559 0.56065184]]
Normalised array is 
 [[0.04906997 0.05927984 0.27789795 0.67779624 0.67634535]
 [0.15398861 0.41181357 0.38812926 0.68556567 0.43133801]
 [0.31505955 0.0700858  0.66172337 0.14100385 0.66186521]
 [0.22540975 0.61772686 0.66993868 0.25118335 0.23599376]
 [0.00601808 0.45611603 0.37064404 0.65482364 0.47513256]]


# 5.  How to find common values between two arrays?

In [27]:
arr3=np.array([10,20,30,40,60])
print("First array is \n",arr3)
arr4=np.array([20,40,60,80,100])
print("Second  array is \n",arr4)
comarr=np.intersect1d (arr3, arr4)
print("Common elements are ",comarr)


First array is 
 [10 20 30 40 60]
Second  array is 
 [ 20  40  60  80 100]
Common elements are  [20 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [37]:
randomArr1= np.random.randint(1,10,size=(2,2))
print("First array is\n",randomArr1)
randomArr2= np.random.randint(1,10,size=(2,2))
print("Second array is\n",randomArr2)
if ((randomArr1==randomArr2).all()==True):
    print("Equal ")
else:
    print("Not equal ")


First array is
 [[3 9]
 [5 9]]
Second array is
 [[6 1]
 [1 5]]
Not equal 


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [41]:
print("Random vector of size 10:\n")
vect= np.random.randint(1,50, size = 10)
print(vect)
vect[vect.argmax()]=0
print("Vector after replacing the max value to 0 :\n",vect)

Random vector of size 10:

[26  6 29 38 30 13  6 25 36 20]
Vector after replacing the max value to 0 :
 [26  6 29  0 30 13  6 25 36 20]


# 9. How to print all the values of an array?

In [43]:
arr5 = np.arange(51)
np.set_printoptions(threshold=np.inf)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


# 10.Subtract the mean of each row of a matrix

In [49]:
print("Original matrix:\n")
arr6= np.random.randint(1,5,size=(3,4))
print(arr6)
print("\nSubtract the mean of each row of the matrix:\n")
arr7 = arr6-arr6.mean(axis=1, keepdims = True)
print(arr7)


Original matrix:

[[4 2 4 1]
 [2 1 3 4]
 [4 1 4 3]]

Subtract the mean of each row of the matrix:

[[ 1.25 -0.75  1.25 -1.75]
 [-0.5  -1.5   0.5   1.5 ]
 [ 1.   -2.    1.    0.  ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [25]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

np.add.at(Z, I, 1)

print(Z)

[1. 1. 4. 3. 5. 3. 4. 2. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [52]:

x= [[1,2],[3,4]]
y = [[5,6],[7,8]]
z = np.diag(np.dot(x,y))
z

array([19, 50])

# 13.How to find the most frequent value in an array?

In [54]:
arr8= np.random.randint(0, 100, 30)
print("Original array:")
print(arr8)
print("Most frequent value in the above array:")
print(np.bincount(arr8).argmax())

Original array:
[41 67 91 73 10 83  8 47 84 64 23 32 25 33 81 41 53 23 69 44 24 54 15 68
 20 68 33 60 38 65]
Most frequent value in the above array:
23


# 14.How to get the n largest values of an array

In [56]:
x = np.arange(99)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[98]


# 15.How to create a record array from a regular array?

In [59]:
a1=np.array(['Veggie','Tomatoes','Chilli ','Carrot','Lemon'])
a2=np.array(['color','Red','Green','Orange','Yellow'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

('Veggie', 'color')
('Tomatoes', 'Red')
('Chilli ', 'Green')
('Carrot', 'Orange')
('Lemon', 'Yellow')
